#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#

name: Compile (py_compile)

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]

jobs:
  compile:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Compile with py_compile
        run: |
          # Run "python -m py_compile" on every .py file under src
          find ./src -name '*.py' | xargs python -m py_compile
      - run: echo "This job's status is ${{ job.status }}."